# encoding: utf-8

module Bluebook
  module Abbreviation
    def self.state(state)
      STATES[state.downcase.capitalize]
    end

    STATES = {
      'Alabama' => 'Ala.',
      'Alaska' => 'Alaska',
      'Arizona' => 'Ariz.',
      'Arkansas' => 'Ark.',
      'California' => 'Cal.',
      'Colorado' => 'Colo.',
      'Connecticut' => 'Conn.',
      'Delaware' => 'Del.',
      'Florida' => 'Fla.',
      'Georgia' => 'Ga.',
      'Hawaii' => 'Haw.',
      'Idaho' => 'Idaho',
      'Illinois' => 'Ill.',
      'Indiana' => 'Ind.',
      'Iowa' => 'Iowa',
      'Kansas' => 'Kan.',
      'Kentucky' => 'Ky.',
      'Louisiana' => 'La.',
      'Maine' => 'Me.',
      'Maryland' => 'Md.',
      'Massachusetts' => 'Mass.',
      'Michigan' => 'Mich.',
      'Minnesota' => 'Minn.',
      'Mississippi' => 'Miss.',
      'Missouri' => 'Mo.',
      'Montana' => 'Mont.',
      'Nebraska' => 'Neb.',
      'Nevada' => 'Nev.',
      'New Hampshire' => 'N.H.',
      'New Jersey' => 'N.J.',
      'New Mexico' => 'N.M.',
      'New York' => 'N.Y.',
      'North Carolina' => 'N.C.',
      'North Dakota' => 'N.D.',
      'Ohio' => 'Ohio',
      'Oklahoma' => 'Okla.',
      'Oregon' => 'Or.',
      'Pennsylvania' => 'Pa.',
      'Rhode Island' => 'R.I.',
      'South Carolina' => 'S.C.',
      'South Dakota' => 'S.D.',
      'Tennessee' => 'Tenn.',
      'Texas' => 'Tex.',
      'Utah' => 'Utah',
      'Vermont' => 'Vt.',
      'Virginia' => 'Va.',
      'Washington' => 'Wash.',
      'West Virginia' => 'W. Va.',
      'Wisconsin' => 'Wis.',
      'Wyoming' => 'Wyo.'
    }

    def self.city(c)
      CITIES.fetch(c, c)
    end

    CITIES = {
      'Baltimore' => 'Balt.',
      'Boston' => 'Bos.',
      'Chicago' => 'Chi.',
      'Dallas' => 'Dall.',
      'District of Columbia' => 'D.C.',
      'Houston' => 'Hous.',
      'Los Angeles' => 'L.A.',
      'New York' => 'N.Y.C.',
      'Philadelphia' => 'Phila.',
      'Phoenix' => 'Phx.',
      'San Francisco' => 'S.F.'
    }

    def self.territory(t)
      TERRITORIES.fetch(t, t)
    end

    TERRITORIES = {
      'American Samoa' => 'Am. Sam.',
      'Guam' => 'Guam',
      'Northern Mariana Islands' => 'N. Mar. I.',
      'Puerto Rico' => 'P.R.',
      'Virgin Islands' => 'V.I.'
    }

    def self.australia(a)
      AUSTRALIA.fetch(a) rescue "No such subdivision: #{a}"
    end

    AUSTRALIA = {
      'Australian Capital Territory' => 'Austl. Cap. Terr.',
      'New South Wales' => 'N.S.W.',
      'Northern Territory' => 'N. Terr.',
      'Queensland' => 'Queensl.',
      'South Australia' => 'S. Austl.',
      'Tasmania' => 'Tas.',
      'Victoria' => 'Vict.',
      'Western Australia' => 'W. Austl.'
    }

    def self.canada(c)
      CANADA.fetch(c) rescue "No such subdivision: #{c}"
    end

    CANADA = {
      'Alberta' => 'Alta.',
      'British Columbia' => 'B.C.',
      'Manitoba' => 'Man.',
      'New Brunswick' => 'N.B.',
      'Newfoundland & Labrador' => 'Nfld.',
      'Northwest Territories' => 'N.W.T.',
      'Nova Scotia' => 'N.S.',
      'Nunavut' => 'Nun.',
      'Ontario' => 'Ont.',
      'Prince Edward Island' => 'P.E.I.',
      'Québec' => 'Que.',
      'Quebec' => 'Que.',
      'Saskatchewan' => 'Sask.',
      'Yukon' => 'Yukon'
    }

    def self.country(c)
      COUNTRIES_AND_REGIONS.fetch(c) rescue raise "No such country: #{c}"
    end

    def self.region(c)
      COUNTRIES_AND_REGIONS.fetch(c) rescue raise "No such region: #{c}"
    end

    COUNTRIES_AND_REGIONS = {
      'Afghanistan' => 'Afg.',
      'Africa' => 'Afr.',
      'Albania' => 'Alb.',
      'Algeria' => 'Alg.',
      'Andorra' => 'Andorra',
      'Angola' => 'Angl.',
      'Anguilla' => 'Anguilla',
      'Antarctica' => 'Antarctica',
      'Antigua & Barbuda' => 'Ant. & Barb.',
      'Argentina' => 'Arg.',
      'Armenia' => 'Arm.',
      'Asia' => 'Asia',
      'Australia' => 'Austl.',
      'Austria' => 'Austria',
      'Azerbaijan' => 'Azer.',
      'Bahamas' => 'Bah.',
      'Bahrain' => 'Bahr.',
      'Bangladesh' => 'Bangl.',
      'Barbados' => 'Barb.',
      'Belarus' => 'Belr.',
      'Belgium' => 'Belg.',
      'Belize' => 'Belize',
      'Benin' => 'Benin',
      'Bermuda' => 'Berm.',
      'Bhutan' => 'Bhutan',
      'Bolivia' => 'Bol.',
      'Bosnia & Herzegovina' => 'Bosn. & Herz.',
      'Botswana' => 'Bots.',
      'Brazil' => 'Braz.',
      'Brunei' => 'Brunei',
      'Bulgaria' => 'Bulg.',
      'Burkina Faso' => 'Burk. Faso',
      'Burundi' => 'Burundi',
      'Cambodia' => 'Cambodia',
      'Cameroon' => 'Cameroon',
      'Canada' => 'Can.',
      'Cape Verde' => 'Cape Verde',
      'Cayman Islands' => 'Cayman Is.',
      'Central African Republic' => 'Cent. Afr. Rep.',
      'Chad' => 'Chad',
      'Chile' => 'Chile',
      'China, People’s Republic of' => 'China',
      'Colombia' => 'Colom.',
      'Comoros' => 'Comoros',
      'Congo, Democratic Republic of the' => 'Dem. Rep. Congo',
      'Congo, Republic of the' => 'Congo',
      'Costa Rica' => 'Costa Rica',
      'Côte d’Ivoire' => 'Côte d’Ivoire',
      'Croatia' => 'Croat.',
      'Cuba' => 'Cuba',
      'Cyprus' => 'Cyprus',
      'Czech Republic' => 'Czech',
      'Denmark' => 'Den.',
      'Djibouti' => 'Djib.',
      'Dominica' => 'Dominica',
      'Dominican Republic' => 'Dom. Rep.',
      'Ecuador' => 'Ecuador',
      'Egypt' => 'Egypt',
      'El Salvador' => 'El Sal.',
      'England' => 'Eng.',
      'Equatorial Guinea' => 'Eq. Guinea',
      'Eritrea' => 'Eri.',
      'Estonia' => 'Est.',
      'Ethiopia' => 'Eth.',
      'Europe' => 'Eur.',
      'Falkland Islands' => 'Falkland Is.',
      'Fiji' => 'Fiji',
      'Finland' => 'Fin.',
      'France' => 'Fr.',
      'Gabon' => 'Gabon',
      'Gambia' => 'Gam.',
      'Georgia' => 'Geor.',
      'Germany' => 'Ger.',
      'Ghana' => 'Ghana',
      'Gibraltar' => 'Gib.',
      'Great Britain' => 'Gr. Brit.',
      'Greece' => 'Greece',
      'Greenland' => 'Green.',
      'Grenada' => 'Gren.',
      'Guadeloupe' => 'Guad.',
      'Guatemala' => 'Guat.',
      'Guinea' => 'Guinea',
      'Guinea-Bissau' => 'Guinea-Bissau',
      'Guyana' => 'Guy.',
      'Haiti' => 'Haiti',
      'Honduras' => 'Hond.',
      'Hong Kong' => 'H.K.',
      'Hungary' => 'Hung.',
      'Iceland' => 'Ice.',
      'India' => 'India',
      'Indonesia' => 'Indon.',
      'Iran' => 'Iran',
      'Iraq' => 'Iraq',
      'Ireland' => 'Ir.',
      'Israel' => 'Isr.',
      'Italy' => 'It.',
      'Jamaica' => 'Jam.',
      'Japan' => 'Japan',
      'Jordan' => 'Jordan',
      'Kazakhstan' => 'Kaz.',
      'Kenya' => 'Kenya',
      'Kiribati' => 'Kiribati',
      'Korea, North' => 'N. Kor.',
      'Korea, South' => 'S. Kor.',
      'Kosovo' => 'Kos.',
      'Kuwait' => 'Kuwait',
      'Kyrgyzstan' => 'Kyrg.',
      'Laos' => 'Laos',
      'Latvia' => 'Lat.',
      'Lebanon' => 'Leb.',
      'Lesotho' => 'Lesotho',
      'Liberia' => 'Liber.',
      'Libya' => 'Libya',
      'Liechtenstein' => 'Liech.',
      'Lithuania' => 'Lith.',
      'Luxembourg' => 'Lux.',
      'Macau' => 'Mac.',
      'Macedonia' => 'Maced.',
      'Madagascar' => 'Madag.',
      'Malawi' => 'Malawi',
      'Malaysia' => 'Malay.',
      'Maldives' => 'Maldives',
      'Mali' => 'Mali',
      'Malta' => 'Malta',
      'Marshall Islands' => 'Marsh. Is.',
      'Martinique' => 'Mart.',
      'Mauritania' => 'Mauritania',
      'Mauritius' => 'Mauritius',
      'Mexico' => 'Mex.',
      'Micronesia' => 'Micr.',
      'Moldova' => 'Mold.',
      'Monaco' => 'Monaco',
      'Mongolia' => 'Mong.',
      'Montenegro' => 'Montenegro',
      'Montserrat' => 'Montserrat',
      'Morocco' => 'Morocco',
      'Mozambique' => 'Mozam.',
      'Myanmar' => 'Myan.',
      'Namibia' => 'Namib.',
      'Nauru' => 'Nauru',
      'Nepal' => 'Nepal',
      'Netherlands' => 'Neth.',
      'New Zealand' => 'N.Z.',
      'Nicaragua' => 'Nicar.',
      'Niger' => 'Niger',
      'Nigeria' => 'Nigeria',
      'North America' => 'N. Am.',
      'Northern Ireland' => 'N. Ir.',
      'Norway' => 'Nor.',
      'Oman' => 'Oman',
      'Pakistan' => 'Pak.',
      'Palau' => 'Palau',
      'Panama' => 'Pan.',
      'Papua New Guinea' => 'Papua N.G.',
      'Paraguay' => 'Para.',
      'Peru' => 'Peru',
      'Philippines' => 'Phil.',
      'Pitcairn Island' => 'Pitcairn Is.',
      'Poland' => 'Pol.',
      'Portugal' => 'Port.',
      'Qatar' => 'Qatar',
      'Réunion' => 'Réunion',
      'Romania' => 'Rom.',
      'Russia' => 'Russ.',
      'Rwanda' => 'Rwanda',
      'Saint Helena' => 'St. Helena',
      'Saint Kitts & Nevis' => 'St. Kitts & Nevis',
      'Saint Lucia' => 'St. Lucia',
      'Saint Vincent & the Grenadines' => 'St. Vincent',
      'Samoa' => 'Samoa',
      'San Marino' => 'San Marino',
      'São Tomé and Príncipe' => 'São Tomé & Príncipe',
      'Saudi Arabia' => 'Saudi Arabia',
      'Scotland' => 'Scot.',
      'Senegal' => 'Sen.',
      'Serbia' => 'Serb.',
      'Seychelles' => 'Sey.',
      'Sierra Leone' => 'Sierra Leone',
      'Singapore' => 'Sing.',
      'Slovakia' => 'Slovk.',
      'Slovenia' => 'Slovn.',
      'Solomon Islands' => 'Solom. Is.',
      'Somalia' => 'Som.',
      'South Africa' => 'S. Afr.',
      'South America' => 'S. Am.',
      'Spain' => 'Spain',
      'Sri Lanka' => 'Sri Lanka',
      'Sudan' => 'Sudan',
      'Suriname' => 'Surin.',
      'Swaziland' => 'Swaz.',
      'Sweden' => 'Swed.',
      'Switzerland' => 'Switz.',
      'Syria' => 'Syria',
      'Taiwan' => 'Taiwan',
      'Tajikistan' => 'Taj.',
      'Tanzania' => 'Tanz.',
      'Thailand' => 'Thai.',
      'Timor-Leste (East Timor)' => 'Timor-Leste',
      'Togo' => 'Togo',
      'Tonga' => 'Tonga',
      'Trinidad & Tobago' => 'Trin. & Tobago',
      'Tunisia' => 'Tunis.',
      'Turkey' => 'Turk.',
      'Turkmenistan' => 'Turkm.',
      'Turks & Caicos Islands' => 'Turks & Caicos Is.',
      'Tuvalu' => 'Tuvalu',
      'Uganda' => 'Uganda',
      'Ukraine' => 'Ukr.',
      'United Arab Emirates' => 'U.A.E.',
      'United Kingdom' => 'U.K.',
      'United States of America' => 'U.S.',
      'Uruguay' => 'Uru.',
      'Uzbekistan' => 'Uzb.',
      'Vanuatu' => 'Vanuatu',
      'Vatican City' => 'Vatican',
      'Venezuela' => 'Venez.',
      'Vietnam' => 'Viet.',
      'Virgin Islands, British' => 'Virgin Is.',
      'Wales' => 'Wales',
      'Yemen' => 'Yemen',
      'Zambia' => 'Zam.',
      'Zimbabwe' => 'Zim.'
    }

    TABLE_10 = [
      STATES,
      COUNTRIES_AND_REGIONS,
      AUSTRALIA,
      CANADA,
      CITIES,
      TERRITORIES
    ].reduce({}) {|m, o| m.merge(o) }
    
    def self.table_10(input)
      TABLE_10.reduce(input) do |mem, pair|
        from, to = pair
        mem.gsub(/\b#{from}\b/, to)
      end
    end
  end
end
